### ISSUE TITLE
The samples module has duplicate dependencies.

### ISSUE THREAD

**Issue by ou-taku14** [guhilling/annotation-processor-demo#21]
The `samples` module has duplicate dependencies which groupId is `org.immutables` and artifactId is `serial` .

**Comment by guhilling** [comment]
I actually can't see the duplicate. I have serial and value, 2 deps? Or am I missing something? Just send me a pull request if there is something I need to correct...

**Comment by guhilling** [comment]
OK, so "serial" is not needed. Thanks!
